// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.27.3
// source: dummyproj/protos/wager.proto

package wager

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Wager_Create_FullMethodName = "/Wager/Create"
)

// WagerClient is the client API for Wager service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type WagerClient interface {
	Create(ctx context.Context, in *CreateRequest, opts ...grpc.CallOption) (*CreateResponse, error)
}

type wagerClient struct {
	cc grpc.ClientConnInterface
}

func NewWagerClient(cc grpc.ClientConnInterface) WagerClient {
	return &wagerClient{cc}
}

func (c *wagerClient) Create(ctx context.Context, in *CreateRequest, opts ...grpc.CallOption) (*CreateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateResponse)
	err := c.cc.Invoke(ctx, Wager_Create_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WagerServer is the server API for Wager service.
// All implementations must embed UnimplementedWagerServer
// for forward compatibility.
type WagerServer interface {
	Create(context.Context, *CreateRequest) (*CreateResponse, error)
	mustEmbedUnimplementedWagerServer()
}

// UnimplementedWagerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedWagerServer struct{}

func (UnimplementedWagerServer) Create(context.Context, *CreateRequest) (*CreateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (UnimplementedWagerServer) mustEmbedUnimplementedWagerServer() {}
func (UnimplementedWagerServer) testEmbeddedByValue()               {}

// UnsafeWagerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WagerServer will
// result in compilation errors.
type UnsafeWagerServer interface {
	mustEmbedUnimplementedWagerServer()
}

func RegisterWagerServer(s grpc.ServiceRegistrar, srv WagerServer) {
	// If the following call pancis, it indicates UnimplementedWagerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Wager_ServiceDesc, srv)
}

func _Wager_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WagerServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Wager_Create_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WagerServer).Create(ctx, req.(*CreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Wager_ServiceDesc is the grpc.ServiceDesc for Wager service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Wager_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "Wager",
	HandlerType: (*WagerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _Wager_Create_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "dummyproj/protos/wager.proto",
}
